/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tasktoo2;

import java.io.File;
import java.util.Scanner;
import javax.xml.parsers.SAXParser;
import javax.xml.parsers.SAXParserFactory;
import org.xml.sax.Attributes;
import org.xml.sax.helpers.DefaultHandler;
import org.json.JSONObject;

public class App {
    public static void main(String[] args) {
        try {
            File inputFile = new File("input.xml");
            SAXParserFactory factory = SAXParserFactory.newInstance();
            SAXParser saxParser = factory.newSAXParser();

            Scanner scanner = new Scanner(System.in);
            System.out.println("Enter comma-separated list of field names to output:");
            String[] selectedFields = scanner.nextLine().split(",");

            JSONObject jsonOutput = new JSONObject();
            DefaultHandler handler = new DefaultHandler() {
                String currentFieldName = "";
                boolean foundField = false;

                public void startElement(String uri, String localName, String qName, Attributes attributes) {
                    if (qName.equalsIgnoreCase("field")) {
                        currentFieldName = attributes.getValue("name");
                    }
                }

                public void characters(char ch[], int start, int length) {
                    String fieldValue = new String(ch, start, length);
                    if (currentFieldName.trim().length() > 0) {
                        for (String fieldName : selectedFields) {
                            if (currentFieldName.equals(fieldName.trim())) {
                                jsonOutput.put(fieldName.trim(), fieldValue);
                                foundField = true;
                                break;
                            }
                        }
                    }
                }

                public void endElement(String uri, String localName, String qName) {
                    if (qName.equalsIgnoreCase("field")) {
                        if (!foundField) {
                            System.out.println(
                                    "Error: Field name \"" + currentFieldName.trim() + "\" not found in XML document.");
                        }
                        currentFieldName = "";
                        foundField = false;
                    }
                }
            };
            saxParser.parse(inputFile, handler);

            System.out.println(jsonOutput.toString());
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
    }
}
