/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tasktoo2;
import java.io.File;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.DocumentBuilder;
import org.w3c.dom.Document;
import org.w3c.dom.NodeList;
import org.w3c.dom.Node;

public class App {
  public static void main(String[] args) {
    try {
      File inputFile = new File("input.xml");
      DocumentBuilderFactory dbFactory = DocumentBuilderFactory.newInstance();
      DocumentBuilder dBuilder = dbFactory.newDocumentBuilder();
      Document doc = dBuilder.parse(inputFile);
      doc.getDocumentElement().normalize();

      NodeList nodeList = doc.getElementsByTagName("field");
      for (int i = 0; i < nodeList.getLength(); i++) {
        Node node = nodeList.item(i);
        if (node.getNodeType() == Node.ELEMENT_NODE) {
          String fieldName = node.getAttributes().getNamedItem("name").getNodeValue();
          String fieldValue = node.getTextContent();
          System.out.println(fieldName + ": " + fieldValue);
        }
      }
    } catch (Exception e) {
      e.printStackTrace();
    }
  }
}

